services:
  ngrok:
    image: ngrok/ngrok:latest
    restart: always
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    command:
      - "http"
      - "host.docker.internal:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "4040:4040"
