apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eurekaservice
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/AceNexus/deploy.git
    targetRevision: main
    path: k8s/eurekaservice
  destination:
    server: https://kubernetes.default.svc
    namespace: acenexus
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
